import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderSite, slugOK } from '../src/render.mjs';
export const root = resolve(fileURLToPath(new URL('..',import.meta.url)));
export function validate(d,m) {
 if(!d.settings?.email || !/^https:\/\/[^/]+$/.test(d.settings.domain)) throw Error('A valid email and HTTPS domain are required');
 for(const key of ['projects','services','journal']) { const seen=new Set(); for(const p of d[key]) {if(!slugOK(p.slug)||seen.has(p.slug)) throw Error(`Invalid or duplicate slug in ${key}`);seen.add(p.slug);} }
 const ids = new Set(d.photos.map(p=>p.id));
 if(ids.size!==d.photos.length)throw Error('Duplicate photo IDs');
 if(d.settings.heroImage&&!ids.has(d.settings.heroImage))throw Error('Hero photograph is missing');
 for(const p of d.photos)if(!m[p.image])throw Error(`Missing image ${p.image}`);
 for(const p of d.projects) for(const id of [p.cover,...p.photos])if(!ids.has(id))throw Error(`Missing project photograph ${id}`);
 for(const p of [...d.services,...d.publications,...d.journal])if(p.image&&!ids.has(p.image))throw Error(`Missing photograph ${p.image}`);
}
export async function build(out=join(root,'.preview')) {
 const d=JSON.parse(await readFile(join(root,'content/site.json'),'utf8')),m=JSON.parse(await readFile(join(root,'content/images.json'),'utf8'));validate(d,m);
 const pages=renderSite(d,m);await mkdir(out,{recursive:true});
 // Remove only pages generated by the previous build, so deleted CMS entries disappear.
 const {unlink}=await import('node:fs/promises');
 try{for(const p of JSON.parse(await readFile(join(out,'.generated.json'),'utf8')))if(!pages.has(p)&&/^\/(?:[a-z0-9-]+\/)*$/.test(p))await unlink(join(out,p.slice(1),'index.html')).catch(()=>{});}catch{}
 for(const [p,html] of pages){const dir=join(out,p.slice(1));await mkdir(dir,{recursive:true});await writeFile(join(dir,'index.html'),html);}
 await cp(join(root,'content/images'),join(out,'images'),{recursive:true});await mkdir(join(out,'assets'),{recursive:true});
 await cp(join(root,'src/fonts'),join(out,'assets/fonts'),{recursive:true});
 for(const f of ['site.css','site.js','mark.svg'])await cp(join(root,'src',f),join(out,'assets',f));
 await writeFile(join(out,'404.html'),pages.get('/404/'));
 await writeFile(join(out,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /admin\nSitemap: ${d.settings.domain}/sitemap.xml\n`);
 await writeFile(join(out,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...pages.keys()].filter(p=>p!=='/404/').map(p=>`<url><loc>${d.settings.domain}${p}</loc></url>`).join('')}</urlset>`);
 await writeFile(join(out,'.generated.json'),JSON.stringify([...pages.keys()]));await writeFile(join(out,'.nojekyll'),'');
 return pages.size;
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const n=await build(process.argv.includes('--publish')?root:undefined);console.log(`Built ${n} pages.`);}
